# ,ggggggggggg,                                                         ,gggg,                                     
#dP"""88""""""Y8,                                               8I    ,88"""Y8b,                                   
#Yb,  88      `8b                                               8I   d8"     `Y8                                   
# `"  88      ,8P                                               8I  d8'   8b  d8                                   
#     88aaaad8P"                                                8I ,8I    "Y88P'                                   
#     88""""",ggggg,   gg,gggg,    gg,gggg,     ,ggg,     ,gggg,8I I8'            ,ggggg,   ,gggggg,   ,ggg,,ggg,  
#     88    dP"  "Y8gggI8P"  "Yb   I8P"  "Yb   i8" "8i   dP"  "Y8I d8            dP"  "Y8gggdP""""8I  ,8" "8P" "8, 
#     88   i8'    ,8I  I8'    ,8i  I8'    ,8i  I8, ,8I  i8'    ,8I Y8,          i8'    ,8I ,8'    8I  I8   8I   8I 
#     88  ,d8,   ,d8' ,I8 _  ,d8' ,I8 _  ,d8'  `YbadP' ,d8,   ,d8b,`Yba,,_____,,d8,   ,d8',dP     Y8,,dP   8I   Yb,
#     88  P"Y8888P"   PI8 YY88888PPI8 YY88888P888P"Y888P"Y8888P"`Y8  `"Y8888888P"Y8888P"  8P      `Y88P'   8I   `Y8
#                      I8          I8                                                                              
#                      I8          I8                                                                              
#                      I8          I8                                                                              
#                      I8          I8                                                                              
#                      I8          I8                                                                              
#                      I8          I8                                                                              
#
#
#   Snowball Lag Machine Fix (AKA The Popcorn Machine) By gluebaby (Undead_Guppy)               Do not redistribute
#
#           Stuck? Ask me a question in the resource thread or in PM's, don't leave a bad review!

snowball-life: 2